### ISSUE TITLE
내 트리 링크 복사하기 관련 이슈 제보

### ISSUE THREAD

**Issue by miraexhoi** [team-socksfactory/naeyangkku-frontend#6]
## 문제 상황
현재 복사되는 링크는 현재 브라우저의 URL을 그대로 가져오고 있습니다.
API 문서 참고하시고 공유용 링크 조회 URL 이 복사되도록 수정해주세요!

<img width="921" alt="스크린샷 2024-12-01 오전 1 05 30" src="https://github.com/user-attachments/assets/1e53e011-329a-4ef5-b032-314a2aba5cb0">

**Comment by wjzlskxk** [comment]
기각
